

web: bench serve  --port 8000


socketio: C:\Program Files\nodejs\node.EXE apps/frappe/socketio.js


watch: bench watch


schedule: bench schedule

worker:  bench worker 1>> logs/worker.log 2>> logs/worker.error.log

